application:
  security:
    pepper: ${TASTETRACKING_SECURITY_PEPPER}
  title: TasteTracking login module
  version: 1.0.0-SNAPSHOT
logging:
  level:
    it:
      uniecampus:
        lfulgione:
          tastetracking:
            ttbe:
              login: DEBUG
    org:
      springframework: INFO
server:
  port: 8081
spring:
  datasource:
    name: ${TASTETRACKING_LOGIN_DB_NAME}
    password: ${TASTETRACKING_LOGIN_DB_PASSWORD}
    url: jdbc:mysql://${TASTETRACKING_LOGIN_DB_ADDRESS}:${TASTETRACKING_LOGIN_DB_PORT}/${TASTETRACKING_LOGIN_DB_NAME}
    username: ${TASTETRACKING_LOGIN_DB_USERNAME}
    # driver-class-name: org.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
